<html>
<head>
    <title>John Deere OAuth2 PHP Example</title>
    <link rel="stylesheet" href="style.css" type="text/css"/>
    <link rel="stylesheet" href="/static/prism.css">
    <style>
        {
            font-family: calibri,helvetica,sans-serif;
        }

        .layout {
            display: grid;
            grid-template-columns: 60% auto;
            grid-gap: 5px;
            padding: 10px;
            background-color: #f2f2f2;
        }

        .grid-container {
            display: grid;
            grid-template-columns: auto;
            grid-gap: 5px;
            padding: 10px;
            background-color: #f2f2f2;
        }

        .grid-container > div {
            font-size: 12px;
            font-weight: bold;
            word-break: break-all;
            overflow:auto;
        }

        p.token {
            font-size: 9px;
            font-weight: normal;
        }

        input {
            width: 100%;
            padding: 5px 10px;
            margin: 2px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type=submit] {
            width: 100%;
            background-color: #4CAF50;
            color: white;
            padding: 5px 10px;
            margin: 8px 0;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        input[type=submit]:hover {
            background-color: #45a049;
        }
    </style>
    <script>
        function toggleDiv(div) {
            var x = document.getElementById(div);
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        }
    </script>
</head>
<body>
<h1>Welcome to the My John Deere API PHP Example.</h1>


<div class="layout">
    <div class="grid-item">
        <div class="grid-container">
            <form action="/" method="post">
                <div class="grid-item">
                    <label id="wellKnownLabel" for="wellKnown">Well-Known Meta:</label><br/>
                    <input type="url" name="wellKnown" id="wellKnown" aria-label="wellKnownLabel" value="<?=$settings['wellKnown']?>"
                           required="true">
                </div>

                <div class="grid-item">
                    <label id="clientIdLabel" for="clientId">Client Id:</label><br/>
                    <input name="clientId" id="clientId" aria-label="clientIdLabel" value="<?=$settings['clientId']?>"
                           required="true">
                </div>

                <div class="grid-item">
                    <label id="clientSecretlabel" for="clientSecret">Client Secret:</label><br/>
                    <input type="password" name="clientSecret" id="clientSecret" aria-label="clientSecretlabel"
                           value="<?=$settings['clientSecret']?>" required="true">
                </div>

                <div class="grid-item">
                    <label id="callBackLabel" for="callbackUrl">Callback URL:</label><br/>
                    <input type="url" name="callbackUrl" id="callbackUrl" aria-label="callBackLabel"
                           value="<?=$settings['callbackUrl']?>"
                           required="true">
                </div>

                <div class="grid-item">
                    <label id="scopesLabel" for="scopes">Requested Scopes:</label><br/>
                    <input name="scopes" id="scopes" aria-label="scopesLabel" value="<?=$settings['scopes']?>" required="true">
                </div>

                <div class="grid-item">
                    <label id="stateLabel" for="state">State (optional):</label><br/>
                    <input name="state" id="state" aria-label="stateLabel" value="<?=$settings['state']?>" required="true">
                </div>

                <div class="grid-item">
                    <input type="submit" value="Connect!">
                </div>

                <div class="grid-item">

                </div>

                <div class="grid-item">

                </div>
            </form>
        </div>
    </div>
    <?php if($settings['accessToken'] !== NULL) { ?>
    <div class="grid-item">
        <div class="grid-container">
            <div class="grid-item">
                Access Token: <br/>
                <?php if($settings['accessToken'] !== NULL) { ?>
                    <p class="token"><?=$settings['accessToken']?><br/> <a onclick="toggleDiv('deets')" href="#">Toggle
                        Details</a>
                    </p>

                    <div id="deets" style="display: none;">
                        <pre><code class="language-json"><?=$settings['accessTokenDetails']?></code></pre>
                    </div>
                <?php } ?>
            </div>

            <div class="grid-item">
                Expiration: <br/>
                <div id="deets"><?=$settings['exp']?></div>
            </div>

            <div class="grid-item">
                Refresh Token: <br/>
                <?php if($settings['refreshToken'] !== NULL) { ?>
                    <p class="token"><?=$settings['refreshToken']?> <br/><a href="/refresh-access-token">Refresh The Access
                        Token</a>
                    </p>
                <?php } ?>
            </div>
        </div>
     <?php } ?>
</div>
</div>
<?php if($settings['accessToken'] !== NULL) { ?>
    <div class="grid-container">
        <form method="post" action="/call-api">
            <div class="grid-item">
                <label id="urlLabel" for="url"> Simple API Invoke With Token:</label>
                <input type="hidden" id="token" name="token" aria-label="urlLabel"
                       value="<?=$settings['accessToken']?>"/>
                <input type="url" id="url" name="url" aria-label="urlLabel"
                       value="<?=$settings['apiUrl']?>/organizations"/>
            </div>
            <div class="grid-item">
                <input type="submit" value="Go!">
            </div>
            <?php if($settings['apiResponse'] !== NULL) { ?>
                <div class="grid-item">
                <pre class="token">
                    <code class="language-json">
                        <?=$settings['apiResponse']?>
                    </code>
                </pre>
                </div>
            <?php } ?>
        </form>

    </div>
<?php } ?>
<!--
<link rel="stylesheet" href="{{ url_for('static', filename='functions.js') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='prism.js') }}">-->
</body>
</html>
